CREATE TABLE IF NOT EXISTS telemetry (
  id BIGSERIAL PRIMARY KEY,
  ts TIMESTAMPTZ NOT NULL,
  source VARCHAR(32) NOT NULL,
  lap INTEGER,
  rpm DOUBLE PRECISION NOT NULL,
  speed_kmh DOUBLE PRECISION NOT NULL,
  engine_temp_c DOUBLE PRECISION NOT NULL,
  cvt_temp_c DOUBLE PRECISION NOT NULL,
  acceleration_g DOUBLE PRECISION NOT NULL,
  incline_deg DOUBLE PRECISION NOT NULL,
  battery_v DOUBLE PRECISION NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  lon DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS telemetry_ts_idx ON telemetry (ts DESC);
CREATE INDEX IF NOT EXISTS telemetry_lap_idx ON telemetry (lap, ts);
